# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ta_app', '0004_auto_20171112_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdetail',
            old_name='task_pk',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='taskdetail',
            name='username',
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='begin_date',
            field=models.DateField(verbose_name='\u6d3e\u5de5\u65e5'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, verbose_name='\u4eba\u6578'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.PositiveIntegerField(verbose_name='\u5831\u916c'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(max_length=256, verbose_name='\u4e3b\u65e8'),
        ),
    ]
