# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ta_app', '0005_auto_20171126_1021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskdetail',
            unique_together=set([('user', 'task')]),
        ),
    ]
