# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ta_app', '0006_auto_20171207_2143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskdetail',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='taskdetail',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TaskDetail',
        ),
    ]
